python: 2.7

install:
  - pip install -i http://pypi.douban.com/simple -U nose
  - pip install -i http://pypi.douban.com/simple -U devicewrapper
  - pip install -i http://pypi.douban.com/simple -U customnoseplugins

before_script:
  - echo "Before script..."
  - which nosetests

script:
  - python run.py --loop 200
#- nosetests --with-plan-loader --loop 50 --with-device-config --with-local-report --verbosity 2

after_script:
  - echo "after_script"
